<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings
  
// Uncomment the next two lines in event of PHP errors:
error_reporting(-1);
ini_set("display_errors", 1);

// 20170905: jobs need to be run through a cronjob
$wgJobRunRate = 0;

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}
date_default_timezone_set('America/Chicago');
$today = getdate();
$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgServer            = "https://doomwiki.org";
$wgCanonicalServer   = "https://doomwiki.org";
$wgSitename          = "DoomWiki.org";
$wgMetaNamespace     = "Doom_Wiki";
$wgMetaNamespaceTalk = "Doom_Wiki_talk";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/w";
$wgArticlePath 	    = "/wiki/$1";
$wgScriptExtension  = ".php";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!

if ($today['mon'] == 12 && $today['mday'] == 10)
	$wgLogo             = "$wgStylePath/Wiki_bday.png";
else
	$wgLogo             = "$wgStylePath/Wiki.png";

// haleyjd 20160211: Security - No account creation through API
$wgAPIModules['createaccount'] = 'ApiDisabled';

// haleyjd 20150812: Apple touch icon
$wgAppleTouchIcon = "/w/images/4/43/Apple-touch-icon.png";

## UPO means: this is also a user preference option
$wgEnableMWSuggest = true;


$wgEnableEmail      = true;
$wgEnableUserEmail  = false; # UPO

$wgEmergencyContact = "admin@doomwiki.org";
$wgPasswordSender = "admin@doomwiki.org";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = getenv('MYSQL_HOSTNAME');
$wgDBname           = getenv('MYSQL_DATABASE');
$wgDBuser           = getenv('MYSQL_USERNAME');
$wgDBpassword       = getenv('MYSQL_PASSWORD');
$wgDBadminuser      = getenv('MYSQL_ADMINUSERNAME');
$wgDBadminpassword  = getenv('MYSQL_ADMINPASSWORD');

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_DB;
$wgSessionCacheType = CACHE_DB;

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgSVGConverter = 'rsvg';

// haleyjd 20120302: add some allowed extensions
// haleyjd 20140314: allow .ico for images
// haleyjd 20140510: allow SVG
$wgFileExtensions = array_merge($wgFileExtensions, array('svg', 'ico', 'lmp', 'wad'));

// haleyjd 20150209: override default thumbnail size (250px vs 300)
$wgDefaultUserOptions['thumbsize'] = 4;

// haleyjd 20170511: enable user CSS and JS
$wgAllowUserCss = true;
$wgAllowUserJs = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";
$wgMaxShellMemory = 512000;

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
$wgCacheDirectory = "$IP/cache";
$wgUseFileCache = false;
$wgShowIPinHeader = false;
## $wgUseGzip = true;

$wgCachePages = true;

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = getenv('WIKI_SECRET_KEY');

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':

$wgDefaultSkin = 'monaco';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage   = "Doom Wiki:Copyrights"; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl    = "https://creativecommons.org/licenses/by-sa/4.0/";
$wgRightsText   = "CC BY-SA 4.0 International";
$wgRightsIcon   = "https://i.creativecommons.org/l/by-sa/4.0/88x31.png";
# $wgRightsCode = "[license_code]"; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );
//$test = true;

//
// Permissions
//

// Implicit group for all logged-in accounts
$wgGroupPermissions['doomer']['move']             = true;
$wgGroupPermissions['doomer']['move-subpages']    = true;
$wgGroupPermissions['doomer']['move-rootuserpages'] = true; // can move root userpages
//$wgGroupPermissions['doomer']['movefile']         = true;	// Disabled for now due to possible bugs and security concerns
$wgGroupPermissions['doomer']['read']             = true;
$wgGroupPermissions['doomer']['edit']             = true;
$wgGroupPermissions['doomer']['createpage']       = true;
$wgGroupPermissions['doomer']['createtalk']       = true;
$wgGroupPermissions['doomer']['writeapi']         = true;
$wgGroupPermissions['doomer']['upload']           = true;
$wgGroupPermissions['doomer']['reupload']         = true;
$wgGroupPermissions['doomer']['reupload-shared']  = true;
$wgGroupPermissions['doomer']['minoredit']        = true;
$wgGroupPermissions['doomer']['purge']            = true; // can use ?action=purge without clicking "ok"
$wgGroupPermissions['doomer']['sendemail']        = true;

// haleyjd 20161006: Deleter group
$wgGroupPermissions['deleter']['delete']          = true;
$wgGroupPermissions['deleter']['bigdelete']       = true;

//
// haleyjd 20140404: other permission tweaks not related to extensions
//

// sysops - wiki community admins
$wgGroupPermissions['sysop']['mergehistory'    ] = true;
$wgGroupPermissions['sysop']['suppressredirect'] = true;

// bureaucrats - server admins
$wgGroupPermissions['bureaucrat']['mergehistory'] = true;

// haleyjd 20220106 - CVE-2021-44857 mitigation
$wgActions['mcrundo'] = false;
$wgActions['mcrrestore'] = false;

//
// Skins
//

wfLoadSkin('CologneBlue');
wfLoadSkin('Modern');
wfLoadSkin('MonoBook');
wfLoadSkin('Vector');

// skin-related config
$wgAllowSiteCSSOnRestrictedPages = true;

// haleyjd 20160411: Needed until update past MW 1.26
// TODO: obsolete, remove me
//$wgAllowMicrodataAttributes = true;

//
// Extensions
//

// haleyjd: moved up
wfLoadExtension("ParserFunctions");

// 20140420: StringFunctions are now integrated into the ParserFunctions module
$wgPFEnableStringFunctions = true;

// 20190428: ReplaceSet extension
require_once("$IP/extensions/ReplaceSet/ReplaceSet.php");

wfLoadExtension("Nuke");
wfLoadExtension("AntiSpoof");
require_once("$IP/extensions/CategoryTree/CategoryTree.php");
wfLoadExtension("CharInsert");
wfLoadExtension("CheckUser");
wfLoadExtension("Cite");
wfLoadExtension("CiteThisPage");

// haleyjd - Description meta tag extension
require_once("$IP/extensions/Description2/Description2.php");
$wgEnableMetaDescriptionFunctions = true;

// haleyjd - DoomWikiAnalytics extension (self-maintained)
require_once("$IP/extensions/DoomWikiAnalytics/DoomWikiAnalytics.php");
$wgDoomWikiGAAccount = 'UA-54071154-1';

// haleyjd - configure QuestyCaptcha
wfLoadExtensions([ "ConfirmEdit", "ConfirmEdit/QuestyCaptcha" ]);
$wgCaptchaClass = 'QuestyCaptcha';

// haleyjd 20140206 - fuck all you idiots paying money for captcha answers; break THIS:
$myChallengeString = substr(base64_encode(md5(uniqid(mt_rand(), true))), 0, 11);
$myChallengeIndex1 = rand(0, 7) + 1;
$myChallengeIndex2 = $myChallengeIndex1 + rand(1, 3);
$myChallengeAnswer = $myChallengeString[$myChallengeIndex1 - 1] . $myChallengeString[$myChallengeIndex2 - 1];
$myChallengePositions = array ('first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', '10th', '11th');
$myChallengePositionName1 = $myChallengePositions[$myChallengeIndex1 - 1];
$myChallengePositionName2 = $myChallengePositions[$myChallengeIndex2 - 1];

$wgCaptchaQuestions[] = array (
  'question' => "Please input the $myChallengePositionName1 and $myChallengePositionName2 characters (with no spaces) from the code <code>$myChallengeString</code>:",
  'answer'   => $myChallengeAnswer
);

// haleyjd 20160212: apply IP blocks to XFF
$wgApplyIpBlocksToXff = true;

wfLoadExtension("DismissableSiteNotice");
require_once("$IP/extensions/FlaggedRevs/FlaggedRevs.php");

// haleyjd 20120514: configuration for FlaggedRevs

// Sysops (ie admins) are implicitly reviewers.
$wgGroupPermissions['sysop']['review'] = true;
$wgGroupPermissions['sysop']['validate'] = true;
$wgGroupPermissions['sysop']['autoreview'] = true;
$wgGroupPermissions['sysop']['unreviewedpages'] = true;
$wgGroupPermissions['sysop']['autoconfirmed'] = true;
$wgGroupPermissions['sysop']['autopatrol'] = true;
$wgGroupPermissions['sysop']['patrol'] = true;

// Editors and Reviewers can skip captchas
$wgGroupPermissions['editor'  ]['skipcaptcha'] = true;
$wgGroupPermissions['reviewer']['skipcaptcha'] = true;

// Reviewers have autopatrol
$wgGroupPermissions['reviewer']['autopatrol'] = true;

// haleyjd 20140530: Settings needed to disable FlaggedRevs from applying to files, due to bugs.
$wgFlaggedRevsNamespaces = array(NS_MAIN);
$wgFlaggedRevsHandleIncludes = FR_INCLUDES_CURRENT;

// haleyjd 20140804: Gadgets extension for in-wiki hosting of JavaScript-based extensions
wfLoadExtension("Gadgets");

wfLoadExtension("ImageMap");

// haleyjd 20140423: Interwiki extension that now ships with MediaWiki
wfLoadExtension("Interwiki");
$wgGroupPermissions['sysop']['interwiki'] = true;

// haleyjd: HideRevision is obsolete; use the below built-in settings instead
$wgGroupPermissions['sysop']['deleterevision'] = true;
$wgGroupPermissions['oversight']['deletelogentry'] = true;
$wgGroupPermissions['oversight']['hideuser'] = true;
$wgGroupPermissions['oversight']['suppressrevision'] = true;
$wgGroupPermissions['oversight']['suppressionlog'] = true;

// haleyjd 20150415: PageImages extension
require_once("$IP/extensions/PageImages/PageImages.php");

// haleyjd 20150402: OpenGraphMeta
require_once("$IP/extensions/OpenGraphMeta/OpenGraphMeta.php");
//$egFacebookAppId = "273122239862290";

wfLoadExtension("Renameuser");
wfLoadExtension("SpamBlacklist");
wfLoadExtension("TitleBlacklist");

// haleyjd - configure title blacklist sources
$wgTitleBlacklistSources = array(
  array(
    'type' => 'localpage',
    'src'  => 'MediaWiki:Titleblacklist',
  ),
  array(
    'type' => 'url',
    'src'  => 'http://meta.wikimedia.org/w/index.php?title=Title_blacklist&action=raw',
  ),
);

// haleyjd 20120618: DNS blacklist configuration
$wgEnableDnsBlacklist = true;
// 20160321: use default blacklist since tornevall is apparently unavailable

require_once("{$IP}/extensions/TorBlock/TorBlock.php");
require_once("{$IP}/extensions/UploadBlacklist/UploadBlacklist.php");
wfLoadExtension("EmbedVideo");

wfLoadExtension("UserMerge");
$wgGroupPermissions['bureaucrat']['usermerge'] = true;

// optional - default is array( 'sysop' )
//$wgUserMergeProtectedGroups = array( 'groupname' );

require_once("{$IP}/extensions/RandomImage/RandomImage.php");
require_once("$IP/extensions/RandomInCategory/RandomInCategory.php");
wfLoadExtension("RandomSelection");

wfLoadExtension("Editcount");

// AbuseFilter
wfLoadExtension("AbuseFilter");
$wgGroupPermissions['sysop']['abusefilter-modify'] = true;
$wgGroupPermissions['sysop']['abusefilter-log-detail'] = true;
$wgGroupPermissions['*']['abusefilter-view'] = true;
$wgGroupPermissions['sysop']['abusefilter-log'] = true;
$wgGroupPermissions['sysop']['abusefilter-private'] = true;
$wgGroupPermissions['sysop']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['sysop']['abusefilter-revert'] = true;

// default thresholds for auto filter disable are far too low - haleyjd 20150324
$wgAbuseFilterEmergencyDisableThreshold['default'] = 0.30;
$wgAbuseFilterEmergencyDisableCount['default'] = 25;

// Monaco Skin
require_once("$IP/skins/monaco/monaco.php");
require_once("$IP/skins/monaco/ExtendedBodyAttributes.php");
require_once("$IP/skins/monaco/ContentRightSidebar.php");

// haleyjd 20140420: No "More" button on Monaco, too glitchy for now.
$wgMonacoUseMoreButton = false;

// Not ready for primetime... most of the themes are a bit broken.
$wgMonacoAllowUsetheme = true;

// haleyjd 20221031: Configure contribution methods
$wgMonacoEnablePaypal = true;
$wgMonacoEnablePatreon = true;
$wgMonacoPaypalID = getenv('WIKI_MONACO_PAYPAL_ID');
$wgMonacoPatreonURL = "https://www.patreon.com/doomwiki";

// haleyjd 20140420: google site verification, meta keywords, and twitter card tags
$wgHooks['BeforePageDisplay'][] = 'wfAddGoogleAndMetas';
function wfAddGoogleAndMetas(&$out, &$skin)
{
  $out->addMeta('google-site-verification', getenv('WIKI_GOOGLE_SITE_VERIFICATION'));
  //$out->addMeta('twitter:card', 'summary');
  //$out->addMeta('twitter:site', '@doomwiki');
  return true;
}

// haleyjd 20140421: semantic link rel canonical generation, works with redirs and oldrevs
$wgHooks['ArticleViewHeader'][] = 'wfAddLinkCanonical';
function wfAddLinkCanonical(&$article, &$outputDone, &$pcache)
{
  $outputPage = $article->getContext()->getOutput();
  if(is_bool($outputPage->getCanonicalUrl()) === true)
  {
    $page  = $article->getPage();
    $title = $article->getTitle();
    if($page->isRedirect())
    {
      $redir = $page->getRedirectTarget();
      if(is_object($redir) && ($redir instanceof Title))
      {
        $title = $redir;
      }
    }
    $outputPage->setCanonicalUrl($title->getFullURL());
  }
  return true;
}

// haleyjd 20140401: robots policy
$wgDefaultRobotPolicy = 'index,nofollow';
$wgNamespaceRobotPolicies =
  array(NS_MAIN     => 'index,follow',
        NS_USER     => 'index,follow',
        NS_PROJECT  => 'index,follow',
        NS_FILE     => 'index,follow',
        NS_HELP     => 'index,follow',
        NS_CATEGORY => 'index,follow');

// haleyjd 20150213: domains allowed to have rel follow in external hyperlinks
$wgNoFollowDomainExceptions[] = 'niwanetwork.org'; // Affiliate: Nintendo Independent Wiki Alliance
$wgNoFollowDomainExceptions[] = 'doomworld.com';   // Doomworld

// haleyjd 20130826: enable IP rangeblocking
$wgSysopRangeBans = true;

// 20140420: Uncomment to enable extensive debugging
$wgShowExceptionDetails = true;
$wgShowSQLErrors = 1;

// 20170924: uncomment and add lines as necessary when needing to do heavy debugging
//$wgDebugLogFile = '/home/doomwiki/logs/debuglog.log';
//$wgDebugLogGroups = array(
//  'torblock' => '/home/doomwiki/logs/torblock.log'
//);

// 20140421: Mobile FrontEnd
wfLoadExtension("MobileFrontend");
$wgMFAutodetectMobileView = true;
$wgMFShowMobileViewToTablets = false; // haleyjd: turned off by request 20220221
$wgMFExtendOpenSearchXml = true;
$wgMobileFrontendFormatCookieExpiry = 2592000; // 30 days (30*24*60*60)
$wgMobileFrontendLogo = "/w/images/e/e9/WikiMobileLogo.png";
//$wgMFDefaultSkinClass = 'SkinMinerva';

// Uncomment to lock database in read-only mode during backups or upgrades (change message if needed):
//$wgReadOnly = "Temporarily locked for upgrade.";
