[www]
user = apache
group = apache
listen = 127.0.0.1:9000
catch_workers_output = yes
decorate_workers_output = no
access.log = /proc/self/fd/1
php_admin_value[error_log] = /proc/self/fd/2
clear_env = no