post_max_size = 128M
upload_max_filesize = 64M
memory_limit = 1024M
max_input_vars = 3000
;extension=sodium.so

; Error logging settings
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
log_errors = On
error_log = /proc/self/fd/2