AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a an EFS file system for use with Fargate services
Parameters:
  EnvironmentName:
    Type: String
    Default: DEV
    Description: The name of the environment to add this service to
  ProjectName:
    Description: Primary project short name
    Type: String
  ContainerSecurityGroup:
    Type: String
    Description: Security group for Fargate containers
  VPCSubnets:
    Description: Comma-separated list of private subnets associated with the existing VPC
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  FileSystemResource:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      FileSystemPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "elasticfilesystem:ClientRootAccess"
              - "elasticfilesystem:ClientWrite"
              - "elasticfilesystem:ClientMount"
            Principal:
              AWS: "*"
            Condition:
              Bool:
                "elasticfilesystem:AccessedViaMountTarget": true
      LifecyclePolicies:
        - TransitionToPrimaryStorageClass: AFTER_1_ACCESS
      FileSystemTags:
        - Key: Name
          Value: Public File Storage

  EFSTargetMount1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !Select [0, !Split [",", !Join [",", !Ref VPCSubnets]]]
      SecurityGroups:
        - !Sub ${ContainerSecurityGroup}

  EFSTargetMount2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !Select [1, !Split [",", !Join [",", !Ref VPCSubnets]]]
      SecurityGroups:
        - !Sub ${ContainerSecurityGroup}

Outputs:
  FileSystemResource:
    Description: General EFS file system resource
    Value: !Ref FileSystemResource
